name: 'user-srv'
host: '10.4.7.71'
port: '50051'
tags:
  - 'imooc'
  - 'user'
  - 'srv'

mysql:
  host: '10.4.7.71'
  port: 3307
  user: 'root'
  password: 'root'
  db: 'mxshop_user_srv'

consul:
  host: '10.4.7.71'
  port: 8500
